/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef acsuser_CONSTANTS_H
#define acsuser_CONSTANTS_H

#include "acsuser_types.h"



class acsuserConstants {
 public:
  acsuserConstants();

};

extern const acsuserConstants g_acsuser_constants;



#endif
