/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "student_constants.h"



const studentConstants g_student_constants;

studentConstants::studentConstants() {
}



