/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef listuser_TYPES_H
#define listuser_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>





typedef struct _User__isset {
  _User__isset() : uid(false), uname(false), usex(false), uage(false), subNodeList(false), subNodeMap(false), subNodeSet(false) {}
  bool uid;
  bool uname;
  bool usex;
  bool uage;
  bool subNodeList;
  bool subNodeMap;
  bool subNodeSet;
} _User__isset;

class User {
 public:

  static const char* ascii_fingerprint; // = "F03610BB0DDEA6AA6B25C17FF584E46D";
  static const uint8_t binary_fingerprint[16]; // = {0xF0,0x36,0x10,0xBB,0x0D,0xDE,0xA6,0xAA,0x6B,0x25,0xC1,0x7F,0xF5,0x84,0xE4,0x6D};

  User() : uid(""), uname(""), usex(0), uage(0) {
  }

  virtual ~User() throw() {}

  std::string uid;
  std::string uname;
  bool usex;
  int16_t uage;
  std::vector<int32_t>  subNodeList;
  std::map<int32_t, std::string>  subNodeMap;
  std::set<int32_t>  subNodeSet;

  _User__isset __isset;

  void __set_uid(const std::string& val) {
    uid = val;
  }

  void __set_uname(const std::string& val) {
    uname = val;
  }

  void __set_usex(const bool val) {
    usex = val;
  }

  void __set_uage(const int16_t val) {
    uage = val;
  }

  void __set_subNodeList(const std::vector<int32_t> & val) {
    subNodeList = val;
  }

  void __set_subNodeMap(const std::map<int32_t, std::string> & val) {
    subNodeMap = val;
  }

  void __set_subNodeSet(const std::set<int32_t> & val) {
    subNodeSet = val;
  }

  bool operator == (const User & rhs) const
  {
    if (!(uid == rhs.uid))
      return false;
    if (!(uname == rhs.uname))
      return false;
    if (!(usex == rhs.usex))
      return false;
    if (!(uage == rhs.uage))
      return false;
    if (!(subNodeList == rhs.subNodeList))
      return false;
    if (!(subNodeMap == rhs.subNodeMap))
      return false;
    if (!(subNodeSet == rhs.subNodeSet))
      return false;
    return true;
  }
  bool operator != (const User &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const User & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};



#endif
