/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "listuser_constants.h"



const listuserConstants g_listuser_constants;

listuserConstants::listuserConstants() {
}



