/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef listuser_CONSTANTS_H
#define listuser_CONSTANTS_H

#include "listuser_types.h"



class listuserConstants {
 public:
  listuserConstants();

};

extern const listuserConstants g_listuser_constants;



#endif
